apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "rodspt/hello-go:v10"

          #Recursos do pods (1 vCPU -> 1000m  - Milicores)  Levar em consideracao o numero de replicas pois vai somar no total
          resources:
            #Recursos minimos  como informar metade 500m ou 0.5
            requests:
              #cpu: 100m
              cpu: "0.05"
              memory: 20Mi
            #Recurso maximo  (Evitar que a soma de tudo ultrapasse o limite do cluster)
            limits:
              #cpu: 500m
              cpu: "0.05"
              memory: 25Mi 
          
          
          #Verifica se ja iniciou
          startupProbe: 
            #Method
            httpGet:  
              #endpoint
              path: /healthz  
              #porta do container nao deve ser do service
              port: 8000  
            #de quanto em quanto deve ser executado
            periodSeconds: 3 
            #quantas vezes pode falhar ate dizer que nao iniciou
            failureThreshold: 30 

          #Verifica se esta ok
          readinessProbe: 
              #Method
            httpGet: 
              #endpoint
              path: /healthz  
              #porta do container nao deve ser do service
              port: 8000  
            #de quanto em quanto deve ser executado
            periodSeconds: 3 
            #quantas vezes tem que falhar para dá o restart padrao 3
            failureThreshold: 1 
            #Tempo minimo de delay (10 + 3 do periodSeconds) se tiver feito o stratupProbe nao precisa
            #initialDelaySeconds: 10 
            
          #Recria o container
          livenessProbe: 
            #Method
            httpGet:  
              #endpoint
              path: /healthz  
              #porta do container nao deve ser do service
              port: 8000  
            #de quanto em quanto deve ser executado
            periodSeconds: 5 
            #quantas vezes tem que falhar para dá o restart padrao 3
            failureThreshold: 2 
            #qual o limite de segundos para uma requisição retornar (se houvesse um teste de banco deveria ser maior)
            timeoutSeconds:  1 
            #quantas vezes tem que testar e dá ok para dá sucesso
            successThreshold: 1 
            #Se tiver feito o stratupProbe nao precisa
            #initialDelaySeconds: 15  

          envFrom:
            - configMapRef:
                name: goserver-env
            - secretRef:
                name: goserver-secret
               
          volumeMounts:
            - mountPath: "/go/myfamily"
              name: config
              readOnly: true
            - mountPath: "/go/pvc"
              name: goserver-volume

          #env por referencia
          #env:
          #  - name: NAME 
          #    valueFrom:
          #      configMapKeyRef:
          #        name: goserver-env
          #        key: NAME
          #
          #  - name: AGE 
          #    valueFrom:
          #      configMapKeyRef:
          #        name: goserver-env
          #        key: AGE



      volumes:
        #poderia ser qualquer nome
        - name: goserver-volume 
          persistentVolumeClaim:
            #esse tem que ser o nome do pvc.yaml
            claimName: goserver-pvc
            #em seguida configurar o volumeMOunts linha 92

        - name: config
          configMap:
            name: configmap-family
            items:
            - key: members
              path: "family.txt"   